apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  # as labels são importante para identificação do pod
  # ela será referenciada na criação do Service
  # podem ser declarada infinitas labes
  labels:
    app: segundo-pod # label: valor
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports:
        - containerPort: 80