apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-sessao
# Neste caso as configurações definirão o armazenamento e criarão dinamicamente o pv
spec:
    accessModes: # dever ser o mesmo modo de acesso que o pv a ser acessado
        - ReadWriteOnce
    resources: # especifica os recursos que o serão utiliizados no statefulset
        requests:
            storage: 1Gi