apiVersion: apps/v1 # Na declaração da versão para o StatefulSet deve ser a versão apps/v1
kind: StatefulSet
metadata:
  name: statefulset-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias # nome para o elemento
      labels:
        app: portal-noticias

    # com o spec definimos o que terá neste pod
    spec:
      # definir os containers presentes no pod
      containers:
        - name: portal-noticias-container # definir o nome
          image: aluracursos/portal-noticias:1 # defini a imagem para criar o container
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          # Declarando o Liveness Probe
          livenessProbe:
            httpGet: # Tipo de requisição a ser feita para o serviço
              path: / # End-Pont de teste da url
              port: 80 # Porta de teste
            periodSeconds: 10 # Intervalo de tempo entre cada verificação
            failureThreshold: 3 # Quantidade de falhas aceitas antes de reiniciar o container
            initialDelaySeconds: 20 # Quantidade de tempo esperar apos o start do container para iniciar os testes
          
          # Declarando o Readiness Probe
          readinessProbe:
            httpGet: # Tipo de requisição a ser feita para o serviço
              path: / # End-Pont de teste da url
              port: 80 # Porta de teste
            periodSeconds: 10 # Intervalo de tempo entre cada verificação
            failureThreshold: 5 # Quantidade de falhas aceitas antes de permitir a entrada de requisições
            initialDelaySeconds: 3 # Quantidade de tempo esperar apos o start do container para iniciar os testes
          
          # Declarando limite de recursos que o container irá utilizar do host
          # Importante para testar o HorizontalPodAutoscaling
          resources: # Definir o recurso
            requests: # define qual recurso
              cpu: 10m # recurso CPU com no máximo 5milicore
  # replicas: 3 # Como o controle de réplicas esta sendo feita pelo HPA, não há a necessidade de declarar as replicas aqui, mantendo assim o padrão de 1 replica.
  selector:
    matchLabels:
      app: portal-noticias
  serviceName: sve-pod-portal-noticias