apiVersion: apps/v1 # Na declaração da versão para o Deployment deve ser a versão apps/v1
kind: Deployment
metadata:
  name: deployment-portal-noticias
spec:
  template:
    metadata:
      name: portal-noticias # nome para o elemento
      labels:
        app: portal-noticias

    # com o spec definimos o que terá neste pod
    spec:
      # definir os containers presentes no pod
      containers:
        - name: portal-noticias-container # definir o nome
          image: aluracursos/portal-noticias:1 # defini a imagem para criar o container
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          # Declarando o Liveness Probe
          livenessProbe:
            httpGet: # Tipo de requisição a ser feita para o serviço
              path: / # End-Pont de teste da url
              port: 80 # Porta de teste
            periodSeconds: 10 # Intervalo de tempo entre cada verificação
            failureThreshold: 3 # Quantidade de falhas aceitas antes de reiniciar o container
            initialDelaySeconds: 20 # Quantidade de tempo esperar apos o start do container para iniciar os testes
          
          # Declarando o Readiness Probe
          readinessProbe:
            httpGet: # Tipo de requisição a ser feita para o serviço
              path: / # End-Pont de teste da url
              port: 80 # Porta de teste
            periodSeconds: 10 # Intervalo de tempo entre cada verificação
            failureThreshold: 5 # Quantidade de falhas aceitas antes de permitir a entrada de requisições
            initialDelaySeconds: 3 # Quantidade de tempo esperar apos o start do container para iniciar os testes
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias