apiVersion: apps/v1 # Na declaração da versão para o ReplicaSet deve ser a versão apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-portal-noticias-pod
spec:
  template: # Aqui será declarado todas as configurações do pod assim como nas declaração normal ocultando apenas o apiVersion e kind
    # com metadados inserimos algumas informações sobre o elemento
    metadata:
      name: portal-noticias # nome para o elemento
      labels:
        app: portal-noticias

    # com o spec definimos o que terá neste pod
    spec:
      # definir os containers presentes no pod
      containers:
        - name: portal-noticias-container # definir o nome
          image: aluracursos/portal-noticias:1 # defini a imagem para criar o container
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  # no mesmo nível do template definimos a quantidade de replicas deveram executar simultaneamente
  replicas: 3

  # Também é necessário fazer uma referência ao tamplate criado através das labels
  selector:
    matchLabels:
      app: portal-noticias # mesma lables declarada no template
